services:
  postgres:
    image: postgres:15
    container_name: ooas-postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-ooas}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
    ports:
      - "5433:5432"
    volumes:
      - ooas-postgres-data:/var/lib/postgresql/data
      - ./db/migration:/docker-entrypoint-initdb.d:ro

volumes:
  ooas-postgres-data:
