services:
  postgres:
    image: postgres:18
    container_name: ooas-postgres
    environment:
      POSTGRES_DB: ooas_spring
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ooas-postgres-data:/var/lib/postgresql

volumes:
  ooas-postgres-data:
