server:
  port: 3000

spring:
  docker:
    compose:
      enabled: false
  application:
    name: ooas
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: false
    ignore-missing-migrations: true

app:
  jwt:
    secret: ${JWT_SECRET:change-this-secret}
    expiration: 24h
  cors:
    allowed-origins: http://localhost:5173
