server:
  port: 3000

spring:
  application:
    name: ooas
  datasource:
    url: jdbc:postgresql://localhost:5432/ooas
    username: postgres
    password: tvantung1904
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    locations: classpath:db/migration

app:
  jwt:
    secret: change-this-secret
    expiration: 24h
  cors:
    allowed-origins: http://localhost:5173
